name: CI Dashboard Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npx tsc --noEmit

      - name: Lint Check
        run: npm run lint

      - name: Build App
        run: npm run build
